parameters:
#    anuncios_anuncio.example.class: Anuncios\AnuncioBundle\Example
    gecko.image_uploader.class: Anuncios\AnuncioBundle\Uploader\ImageUploader
    gecko.listener.image_upload.class: Anuncios\AnuncioBundle\EventListener\ImageUploadListener

services:
#    anuncios_anuncio.example:
#        class: %anuncios_anuncio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    fabpot.twig.intl_extension:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    
    anuncios_anuncio.frontend.listener:
        class: Anuncios\AnuncioBundle\EventListener\FrontendListener
        arguments: ["@service_container", "@controller_resolver"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            
    anuncios_anuncio.backend.menu_builder:
        class: Anuncios\AnuncioBundle\Menu\BackendMenuBuilder
        arguments: ["@knp_menu.factory"]
        
    anuncios_anuncio.backend.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: anuncios_anuncio.backend.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: backend_main_menu } # The alias is what is used to retrieve the menu
            
    anuncios.form.type.anuncio:
        class: Anuncios\AnuncioBundle\Form\Type\AnuncioType
        tags:
            - { name: form.type, alias: anuncios_anuncio }
            
    anuncios.form.type.campaign:
        class: Anuncios\AnuncioBundle\Form\Type\CampaignType
        tags:
            - { name: form.type, alias: anuncios_campaign }
            
    anuncios.form.type.sector:
        class: Anuncios\AnuncioBundle\Form\Type\SectorType
        tags:
            - { name: form.type, alias: anuncios_sector }
            
    anuncios.form.type.category:
        class: Anuncios\AnuncioBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: anuncios_category }

    anuncios.form.type.user:
        class: Anuncios\AnuncioBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: anuncios_user }
            
    anuncios.form.type.filter.user:
        class: Anuncios\AnuncioBundle\Form\Type\Filter\UserFilterType
        tags:
            - { name: form.type, alias: anuncios_user_filter }