parameters:
#    anuncios_anuncio.example.class: Anuncios\AnuncioBundle\Example
    gecko.image_uploader.class: Anuncios\AnuncioBundle\Uploader\ImageUploader
    gecko.listener.image_upload.class: Anuncios\AnuncioBundle\EventListener\ImageUploadListener

services:
#    anuncios_anuncio.example:
#        class: %anuncios_anuncio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    gecko.knp_gaufrette.filesystem:
        class: Gaufrette\Filesystem
        factory_service:  knp_gaufrette.filesystem_map
        factory_method:   get
        arguments: [ "gecko_image" ]
    
    gecko.image_uploader:
        class: %gecko.image_uploader.class%
        arguments: ["@gecko.knp_gaufrette.filesystem"]
        
    gecko.listener.image_upload:
        class: %gecko.listener.image_upload.class%
        arguments: ["@gecko.image_uploader"]
        tags:
            - { name: kernel.event_listener, event: anuncios.anuncio.pre_create, method: uploadImage }
            - { name: kernel.event_listener, event: anuncios.anuncio.pre_update, method: uploadImage }
    
    anuncios_anuncio.backend.menu_builder:
        class: Anuncios\AnuncioBundle\Menu\BackendMenuBuilder
        arguments: ["@knp_menu.factory"]
        
    anuncios_anuncio.backend.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: anuncios_anuncio.backend.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: backend_main_menu } # The alias is what is used to retrieve the menu
            
    anuncios.form.type.anuncio:
        class: Anuncios\AnuncioBundle\Form\Type\AnuncioType
        tags:
            - { name: form.type, alias: anuncios_anuncio }
            
    anuncios.form.type.campaign:
        class: Anuncios\AnuncioBundle\Form\Type\CampaignType
        tags:
            - { name: form.type, alias: anuncios_campaign }
            
    anuncios.form.type.sector:
        class: Anuncios\AnuncioBundle\Form\Type\SectorType
        tags:
            - { name: form.type, alias: anuncios_sector }
            
    anuncios.form.type.category:
        class: Anuncios\AnuncioBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: anuncios_category }
