Anuncios\AnuncioBundle\Entity\Anuncio:
    properties:
        name:
            - NotBlank: ~
        agency:
            - NotBlank: ~
        advertiser:
            - NotBlank: ~
        product:
            - NotBlank: ~
        brand:
            - NotBlank: ~

Anuncios\AnuncioBundle\Entity\Campaign:
    properties:
        name:
            - NotBlank: ~