anuncios_anuncio_login:
    pattern: /login
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Security:login }
    
anuncios_anuncio_logout:
    pattern: /logout
    defaults: { _controller: FosUserBundle:Security:logout }

anuncios_anuncio_index:
    pattern:  /
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:index }

anuncios_anuncio_category:
    pattern:  /categoria/{id}
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:category }
    
anuncios_anuncio_show:
    pattern:  /anuncio/{id}
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:show }
    
anuncios_anuncio_vote:
    pattern: /anuncio/{id}/votar
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:vote }
    
anuncios_anuncio_desvote:
    pattern: /anuncio/{id}/desvotar
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:desvote }
    
anuncios_anuncio_ranking_usuario:
    pattern: /ranking/usuario/{id}
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:rankingUsuario }
    
anuncios_anuncio_ranking_jurado:
    pattern: /ranking/jurado/{id}
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:rankingJurado }
