anuncios_anuncio_login:
    pattern: /login
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Security:login }
    
anuncios_anuncio_logout:
    pattern: /logout
    defaults: { _controller: FosUserBundle:Security:logout }

anuncios_anuncio_index:
    pattern:  /
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:index }
    
anuncios_anuncio_home:
    pattern:  /home
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:home }
    
anuncios_anuncio_category:
    pattern:  /category/{id}
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:category }
    
anuncios_anuncio_show:
    pattern:  /anuncio/show/{id}
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:show }
    
anuncios_anuncio_vote:
    pattern: /anuncio/{id}/vote
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:vote }
