anuncios_anuncio_index:
    pattern:  /
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:index }
    
anuncios_anuncio_home:
    pattern:  /home
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:home }
    
anuncios_anuncio_category:
    pattern:  /home/category/{id}
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:category }
    
anuncios_anuncio_show:
    pattern:  /home/anuncio/show/{id}
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:show }
    
anuncios_anuncio_vote:
    pattern: /home/anuncio/{id}/vote
    defaults: { _controller: AnunciosAnuncioBundle:Frontend/Main:vote }
