Anuncios\AnuncioBundle\Entity\Anuncio:
    type: entity
    repositoryClass: Anuncios\AnuncioBundle\Entity\AnuncioRepository
    table: anuncio
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        agency:
            type: string
            length: 255
        advertiser:
            type: string
            length: 255
        product:
            type: string
            length: 255
        brand:
            type: string
            length: 255
        otherFields:
            type: array
            column: other_fields
        image:
            type: string
            length: 255
        finalistType:
            type: string
            length: 255
            nullable: true
        votoJurado:
            type: integer
            nullable: true
            column: voto_jurado
        votoUsuario:
            type: integer
            nullable: true
            column: voto_usuario
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
        anuncioId:
            column: anuncio_id
            type: integer
            nullable: true
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: anuncios
            joinColumn:
                name: category_id
                referencedColumnName: id
                onDelete: CASCADE
        campaign:
            targetEntity: Campaign
            inversedBy: anuncios
            joinColumn:
                name: campaign_id
                referencedColumnName: id
                onDelete: CASCADE
        sector:
            targetEntity: Sector
            inversedBy: anuncios
            joinColumn:
                name: sector_id
                referencedColumnName: id
                onDelete: CASCADE
    oneToMany:
        resources:
            targetEntity: Resource
            mappedBy: anuncio
        voting:
            targetEntity: Voting
            mappedBy: anuncio
    lifecycleCallbacks: {  }
