Anuncios\AnuncioBundle\Entity\Campaign:
    type: entity
    table: campaign
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        isActive:
            type: boolean
            column: is_active
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    oneToMany:
        anuncios:
            targetEntity: Anuncio
            mappedBy: campaign
    lifecycleCallbacks: {  }
