Anuncios\AnuncioBundle\Entity\Campaign:
    type: entity
    repositoryClass: Anuncios\AnuncioBundle\Entity\CampaignRepository
    table: campaign
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        isActive:
            type: boolean
            column: is_active
        showFinalist:
            type: boolean
            column: show_finalist
        dateBegin:
            type: date
            column: date_begin
            nullable: true
        dateEnd:
            type: date
            column: date_end
            nullable: true
        month:
            type: integer
            nullable: true
        year:
            type: integer
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    oneToMany:
        anuncios:
            targetEntity: Anuncio
            mappedBy: campaign
    lifecycleCallbacks: {  }
