Anuncios\AnuncioBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        headlineImage:
            column: headline_image
            type: string
            length: 255
            nullable: true
        slug:
            column: slug
            type: string
            unique: true
            nullable: true
            gedmo:
                slug:
                    fields: [ name ]
                    unique: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    indexes:
        search_idx:
            columns: slug
    oneToMany:
        anuncios:
            targetEntity: Anuncio
            mappedBy: category
    lifecycleCallbacks: {  }
