Anuncios\AnuncioBundle\Entity\Configuration:
    type: entity
    table: configuration
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titleHomeImage:
            type: string
            length: 255 
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update