Anuncios\AnuncioBundle\Entity\Resource:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
        link:
            type: string
            length: 255
        name:
            type: string
            length: 255
    manyToOne:
        anuncio:
            targetEntity: Anuncio
            inversedBy: resources
            joinColumn:
                name: anuncio_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
