Anuncios\AnuncioBundle\Entity\Sector:
    type: entity
    table: sector
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: auto
    fields:
        name:
            type: string
            length: 255
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    oneToMany:
        anuncios:
            targetEntity: Anuncio
            mappedBy: sector
    lifecycleCallbacks: {  }
