Anuncios\AnuncioBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        name:
            type: string
            length: 255
            nullable: true
        surname:
            type: string
            length: 255
            nullable: true
        isJurado:
            type: boolean
            column: is_jurado
            default: false
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    oneToMany:
        voting:
            targetEntity: Voting
            mappedBy: user
    lifecycleCallbacks: {  }
