Anuncios\AnuncioBundle\Entity\Voting:
    type: entity
    repositoryClass: Anuncios\AnuncioBundle\Entity\VotingRepository
    table: voting
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    manyToOne:
        user:
            targetEntity: User
            inversedBy: voting
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
        anuncio:
            targetEntity: Anuncio
            inversedBy: voting
            joinColumn:
                name: anuncio_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
