anuncios_anuncio_backend_anuncio_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: anuncios.controller.anuncio:indexAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/Anuncio:index.html.twig
            paginate: 100
            
anuncios_anuncio_backend_anuncio_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: anuncios.controller.anuncio:createAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/Anuncio:create.html.twig
            redirect: anuncios_anuncio_backend_anuncio_update

anuncios_anuncio_backend_anuncio_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: anuncios.controller.anuncio:updateAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/Anuncio:update.html.twig
            redirect: anuncios_anuncio_backend_anuncio_update

anuncios_anuncio_backend_anuncio_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: anuncios.controller.anuncio:deleteAction
        _sylius:
            redirect: anuncios_anuncio_backend_anuncio_index