anuncios_anuncio_backend_configuration_index:
    pattern: /
    defaults: { _controller: anuncios.controller.configuration:indexAction }

anuncios_anuncio_backend_configuration_update:
    pattern: /edit
    methods: [GET, PUT, POST]
    defaults: 
        _controller: anuncios.controller.configuration:updateAction
        _sylius:
            redirect: anuncios_anuncio_backend_configuration_index