anuncios_anuncio_backend_jury_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: anuncios.controller.jury:indexAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/Jury:index.html.twig
            paginate: 100
            
anuncios_anuncio_backend_jury_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: anuncios.controller.jury:createAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/Jury:create.html.twig
            redirect: anuncios_anuncio_backend_jury_update

anuncios_anuncio_backend_jury_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: anuncios.controller.jury:updateAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/Jury:update.html.twig
            redirect: anuncios_anuncio_backend_jury_update

anuncios_anuncio_backend_jury_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: anuncios.controller.jury:deleteAction
        _sylius:
            redirect: anuncios_anuncio_backend_jury_index