anuncios_anuncio_backend_campaign:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/campaign.yml
    prefix: /campaign
    
anuncios_anuncio_backend_anuncio:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/anuncio.yml
    prefix: /anuncios

anuncios_anuncio_backend_sector:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/sector.yml
    prefix: /sector

anuncios_anuncio_backend_category:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/category.yml
    prefix: /category

anuncios_anuncio_backend_jury:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/jury.yml
    prefix: /jury