gecko_backend_dashboard:
    pattern: /dashboard
    defaults: { _controller: AnunciosAnuncioBundle:Backend/Dashboard:main }

anuncios_anuncio_backend_campaign:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/campaign.yml
    prefix: /campaign
    
anuncios_anuncio_backend_anuncio:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/anuncio.yml
    prefix: /anuncios

anuncios_anuncio_backend_sector:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/sector.yml
    prefix: /sector

anuncios_anuncio_backend_category:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/category.yml
    prefix: /category

anuncios_anuncio_backend_user:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/user.yml
    prefix: /user
    
anuncios_anuncio_backend_configuration:
    resource: @AnunciosAnuncioBundle/Resources/config/routing/backend/configuration.yml
    prefix: /configuraciones

change_pass_user:
    pattern: /change
    defaults: { _controller: AnunciosAnuncioBundle:Backend/Change:main }