anuncios_anuncio_backend_sector_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: anuncios.controller.sector:indexAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/Sector:index.html.twig
            paginate: 100
            
anuncios_anuncio_backend_sector_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: anuncios.controller.sector:createAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/Sector:create.html.twig
            redirect: anuncios_anuncio_backend_sector_update

anuncios_anuncio_backend_sector_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: anuncios.controller.sector:updateAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/Sector:update.html.twig
            redirect: anuncios_anuncio_backend_sector_update

anuncios_anuncio_backend_sector_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: anuncios.controller.sector:deleteAction
        _sylius:
            redirect: anuncios_anuncio_backend_sector_index