anuncios_anuncio_backend_user_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: anuncios.controller.user:indexAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/User:index.html.twig
            paginate: 100
            
anuncios_anuncio_backend_user_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: anuncios.controller.user:createAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/User:create.html.twig
            redirect: anuncios_anuncio_backend_user_update

anuncios_anuncio_backend_user_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: anuncios.controller.user:updateAction
        _sylius:
            template: AnunciosAnuncioBundle:Backend/User:update.html.twig
            redirect: anuncios_anuncio_backend_user_update

anuncios_anuncio_backend_user_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: anuncios.controller.user:deleteAction
        _sylius:
            redirect: anuncios_anuncio_backend_user_index