fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
gecko_backend_index:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: gecko_backend_dashboard
        permanent: true

#sylius_backend_settings:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/settings.yml
#    prefix: /settings
