<?php

namespace Anuncios\AnuncioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnuncioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnuncioRepository extends EntityRepository
{
	public function getAnunciosByCategory($campaign, $category)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT a
				FROM AnunciosAnuncioBundle:Anuncio a
				WHERE a.campaign = :campaign AND a.category = :category
				ORDER BY a.createdAt DESC'
		)->setParameters(array(
			'campaign' => $campaign,
			'category' => $category
		))
		->getResult();
	}
	
	public function getLeftAnunciosVoteByUser($campaign, $user, $limit)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT a
				FROM AnunciosAnuncioBundle:Anuncio a
				WHERE a.campaign = :campaign AND a.id NOT IN (
					SELECT IDENTITY(v.anuncio) FROM AnunciosAnuncioBundle:Voting v WHERE v.user = :user
				)'
		)->setParameters(array(
				'campaign' => $campaign,
				'user' => $user
		))
		->setMaxResults($limit)
		->getResult();
	}
	
	public function getLastAnunciosVote($campaign, $limit)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT a
				FROM AnunciosAnuncioBundle:Anuncio a
				WHERE a.campaign = :campaign AND a.id IN (
					SELECT IDENTITY(v.anuncio) FROM AnunciosAnuncioBundle:Voting v ORDER BY v.createdAt DESC
				)'
		)->setParameter('campaign', $campaign)
		->setMaxResults($limit)
		->getResult();
	}
	
	public function getLastAnunciosVoteByCategory($campaign, $category, $limit)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT a
				FROM AnunciosAnuncioBundle:Anuncio a
				WHERE a.campaign = :campaign AND a.category = :category AND a.id IN (
					SELECT IDENTITY(v.anuncio) FROM AnunciosAnuncioBundle:Voting v ORDER BY v.createdAt DESC
				)'
		)->setParameters(array(
				'campaign' => $campaign,
				'category' => $category
		))
		->setMaxResults($limit)
		->getResult();
	}
	
	public function getAnunciosVoteByJurado($campaign, $limit)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT a 
				FROM AnunciosAnuncioBundle:Anuncio a
				WHERE a.campaign = :campaign
				ORDER BY a.votoJurado DESC'
		)->setParameter('campaign', $campaign)
		->setMaxResults($limit)
		->getResult();
	}
	
	public function getAnunciosVoteByUsuario($campaign, $limit)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT a
				FROM AnunciosAnuncioBundle:Anuncio a 
				WHERE a.campaign = :campaign
				ORDER BY a.votoUsuario DESC'
		)->setParameter('campaign', $campaign)
		->setMaxResults($limit)
		->getResult();
	}
}
