<?php

namespace Anuncios\AnuncioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function hasVotingByCategory($campaign, $category)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT count(u) 
				FROM AnunciosAnuncioBundle:User u 
				INNER JOIN AnunciosAnuncioBundle:Voting v WITH u.id = v.user
				INNER JOIN AnunciosAnuncioBundle:Anuncio a WITH a.id = v.anuncio 
				WHERE a.campaign = :campaign AND a.category = :category'
		)->setParameters(array(
			'campaign' => $campaign,
			'category' => $category
		))
		->getSingleScalarResult();
	}
}
