<?php

namespace Anuncios\AnuncioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VotingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotingRepository extends EntityRepository
{
	public function hasVoting($user, $anuncio)
	{
		return $this->getEntityManager()
		->createQuery(
			'SELECT v FROM AnunciosAnuncioBundle:Voting v WHERE v.user = :user AND v.anuncio = :anuncio'
		)->setParameters(array(
    		'user' => $user,
    		'anuncio'  => $anuncio
		))	
		->getResult();
	}
	
	public function getLastVoting($limit)
	{
		return $this->getEntityManager()
		->createQuery(
			'SELECT v FROM AnunciosAnuncioBundle:Voting v ORDER BY v.createdAt'
		)->setMaxResults($limit)
		->getResult();
	}
}
